baseURL = "http://napo5.github.io/"
languageCode = "en-us"
title = "Luca Pretini"
theme = "soho"

[params]

profilePicture = "profilo.png"

themeColor = "#484ca8"

mainSections = ["projects"]

[menu]

	#[[menu.main]]
	#name ="Projects"
	#weight="100"
	#identifier="projects"
	#url = "/projects/"
	
	[[menu.main]]
	name ="Chi sono"
	weight="100"
	identifier="aboutme"
	url = "/aboutme"






  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/luca-pretini/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/napo5"
  
  [[params.socialIcons]]
  icon = "fa-telegram"
  title = "Telegram"
  url = "https://t.me/napo5"



